[package]
name = "datafusion-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
datafusion = "39.0.0"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }

[[example]]
name = "csv_sql"
path = "examples/csv_sql.rs"

